[tool.poetry]
name = "mapserver"
version = "0.13.0"
description = ""
authors = ["David Brooks <d.brooks@auckland.ac.nz>"]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
flask = "^2.2.2"
gunicorn = "^20.1.0"
landez = "^2.5.0"
flask-cors = "^3.0.10"
flatmapknowledge = {url="https://github.com/AnatomicMaps/flatmap-knowledge/releases/download/v1.4.1/flatmapknowledge-1.4.1-py3-none-any.whl"}
github-flask = {url="https://github.com/dbrnz/github-flask/releases/download/v3.2.1/github_flask-3.2.1-py3-none-any.whl"}
Pillow = "^9.3.0"
cors-testing = "^0.4.0"

[tool.poetry.dev-dependencies]
sphinx = "4.0.3"
sphinx-rtd-theme = "*"
sphinxcontrib-httpdomain = "*"

[tool.poetry.scripts]
mapserver = 'mapserver.__main__:main'
mapviewer = 'mapserver.__main__:viewer'

[build-system]
# See https://github.com/chrahunt/rtd-poetry/issues/3
requires = ["poetry_core>=1.0.0", "rtd-poetry @ https://github.com/dbrnz/rtd-poetry/archive/refs/tags/v0.1.2.tar.gz"]
build-backend = "rtd_poetry"
