[tool.poetry]
name = "mapserver"
version = "0.26.4"
description = ""
authors = ["David Brooks <d.brooks@auckland.ac.nz>"]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
landez = "^2.5.0"
flatmapknowledge = {url="https://github.com/AnatomicMaps/flatmap-knowledge/releases/download/v2.0.2/flatmapknowledge-2.0.2-py3-none-any.whl"}
mapmaker = {url="https://github.com/AnatomicMaps/flatmap-maker/releases/download/v1.15.1/mapmaker-1.15.1-py3-none-any.whl"}
Pillow = "^10.3.0"
requests = "^2.31.0"
hypercorn = "^0.16.0"
rdflib = ">=7.0.0"
tqdm = "^4.66.5"
setuptools = "^75.1.0"
litestar = "^2.13.0"
uvloop = "^0.21.0"
structlog = "^24.4.0"
rich = "^13.9.4"
pyyaml = "^6.0.2"

[tool.poetry.dev-dependencies]
sphinx = "^8.1"
sphinx-rtd-theme = "^3.0.1"
sphinxcontrib-httpdomain = "*"

[tool.poetry.scripts]
mapserver = 'mapserver.__main__:mapserver'
mapviewer = 'mapserver.__main__:mapviewer'

[tool.poetry.group.dev.dependencies]
uvicorn = "^0.32.0"

[build-system]
# See https://github.com/chrahunt/rtd-poetry/issues/3
requires = ["poetry_core>=1.0.0", "rtd-poetry @ https://github.com/dbrnz/rtd-poetry/archive/refs/tags/v0.1.2.tar.gz"]
build-backend = "rtd_poetry"

[tool.pyright]
pythonVersion = "3.12"
venvPath = "."
venv = ".venv"
