[tool.poetry]
name = "mapserver"
version = "0.21.2"
description = ""
authors = ["David Brooks <d.brooks@auckland.ac.nz>"]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
landez = "^2.5.0"
flatmapknowledge = {url="https://github.com/AnatomicMaps/flatmap-knowledge/releases/download/v1.7.1/flatmapknowledge-1.7.1-py3-none-any.whl"}
Pillow = "^10.3.0"
mapmaker = { path = "./mapmaker", develop = true }
quart = "^0.19.5"
quart-cors = "^0.7.0"
requests = "^2.31.0"
uvloop = "^0.19.0"
hypercorn = "^0.16.0"

[tool.poetry.dev-dependencies]
sphinx = "4.0.3"
sphinx-rtd-theme = "*"
sphinxcontrib-httpdomain = "*"

[tool.poetry.scripts]
mapserver = 'mapserver.__main__:mapserver'
mapviewer = 'mapserver.__main__:mapviewer'

[build-system]
# See https://github.com/chrahunt/rtd-poetry/issues/3
requires = ["poetry_core>=1.0.0", "rtd-poetry @ https://github.com/dbrnz/rtd-poetry/archive/refs/tags/v0.1.2.tar.gz"]
build-backend = "rtd_poetry"

[tool.pyright]
pythonVersion = "3.12"
venvPath = "."
venv = ".venv"
