[tool.poetry]
name = "mapserver"
version = "0.12.2"
description = ""
authors = ["David Brooks <d.brooks@auckland.ac.nz>"]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
flask = "*"
gunicorn = "*"
landez = "*"
flask-cors = "*"
flatmapknowledge = {url="https://github.com/AnatomicMaps/flatmap-knowledge/releases/download/v1.1.4/flatmapknowledge-1.1.4-py3-none-any.whl"}
Pillow = "^9.2.0"

[tool.poetry.dev-dependencies]
sphinx = "4.0.3"
sphinx-rtd-theme = "*"
sphinxcontrib-httpdomain = "*"

[tool.poetry.scripts]
mapserver = 'mapserver.__main__:main'
mapviewer = 'mapserver.__main__:viewer'

[build-system]
# See https://github.com/chrahunt/rtd-poetry/issues/3
requires = ["poetry_core>=1.0.0", "rtd-poetry @ https://github.com/dbrnz/rtd-poetry/archive/refs/tags/v0.1.2.tar.gz"]
build-backend = "rtd_poetry"
