[project]
name = "tools"
version = "0.1.0"
description = "Tools and utilities for working with flatmap servers."
authors = [
    { name = "David Brooks", email = "<d.brooks@auckland.ac.nz>"}
]
requires-python = "==3.12.*"
dependencies = [
    "prompt-toolkit>=3.0.51",
    "requests>=2.32.3",
]
